-- MySQL Script generated by MySQL Workbench
-- Sun Mar 27 18:47:04 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MultiTest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MultiTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MultiTest` DEFAULT CHARACTER SET utf8 ;
USE `MultiTest` ;

-- -----------------------------------------------------
-- Table `MultiTest`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultiTest`.`User` ;

CREATE TABLE IF NOT EXISTS `MultiTest`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
